server:
  port: 8084

spring:
  application:
    name: API-GATEWAY	


  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        predicates:
        - Path=/user/**
        uri: lb://USER-SERVICE

      - id: HOTEL-SERVICE
        predicates:
        - Path=/hotel/**
        uri: lb://HOTEL-SERVICE

      - id: RATING-SERVICE
        predicates:
        - Path=/rating/**
        uri: lb://RATING-SERVICE
  config:
    import:
    - configserver:http://localhost:8085

